### PR TITLE
Patch dhcpcd rather than change version

### LINKED ISSUE #70: [Buildroot Package] - DHCPCD version resets to upstream
### Observed Behavior

When using a docker, a fresh build does successfully build dhcpcd v 10.0.5 using the pre-make-common.sh script.  However, sometimes it resets this back to v10.0.4.

### Expected Behavior

DHCPCD should remain v10.0.5 no matter how a build is triggered.

### Steps to Reproduce

1. Run and open docker, run a clean build
2. use docker exec to get a nother terminal
3. run a partial build from their (i.e. a -dirclean then a make)
4. Obverse sometimes it rebuilds dhcpcd as v10.0.4.

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by jr1221**
## Changes

Rather than use dhcpcd v10.0.5, path v10.0.4 to fix issue.  This removes hacky need for pre-make-common, which was sometimes failing and leaving systems pretty much unusable.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [X] No merge conflicts
- [n/a] All checks passing
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #70

### CODE REVIEW

File: odysseus/odysseus_tree/pre-make-common.sh [hunk 1]
```diff
@@ -1,11 +1,11 @@
...
 
-SCRIPT_DIR="$(dirname "$(realpath "$0")")"
-
-echo "change dhcpcd version to 10.0.5 from 10.0.4"
-cd $SCRIPT_DIR/../buildroot/package/dhcpcd/ || exit
-# remove integrity file for dhcpcd 10.0.4
-rm ./dhcpcd.hash
-# replace old version with new one
-sed -i 's/DHCPCD_VERSION = 10.0.4/DHCPCD_VERSION = 10.0.5/g' dhcpcd.mk
+# SCRIPT_DIR="$(dirname "$(realpath "$0")")"
```
Comment (nwdepatie) [inline odysseus/odysseus_tree/pre-make-common.sh:3]: Can we not just delete this file?

**Review by nwdepatie — APPROVED** [review]
Looks good to me, does seem cleaner this way. Can we remove the premake script though?
